services:
  registry:
    restart: always
    # Docker 'registry' releases: https://github.com/distribution/distribution/releases
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - registry-data:/var/lib/registry

volumes:
  registry-data: {}
