# See https://hub.docker.com/_/docker
FROM docker:28-dind

# Copy our demonstration script into the image for convenience
COPY dind-demo.sh /usr/local/bin/dind-demo.sh
RUN chmod +x /usr/local/bin/dind-demo.sh
