name: Run the 'compose/' sub-project

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run-the-compose-sub-project:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Bring the containers up
        working-directory: compose/
        run: docker-compose up
